### PR TITLE
feat: add stytch.AttributesFromRequest

### PR DESCRIPTION
**Pull request by josharian**
Most attributes are going to be parsed out of an http.Request.
May as well make it easy.

### CODE REVIEW

**Comment by jeremy-stytch** [comment]
Hi @josharian, thanks for opening a PR! However, this doesn't fit our current goals for this library, so I'm going to close it.

Right now, we're focused on handling interactions with the Stytch API itself to provide flexibility for apps to use that however they want. Since there are other ways besides RemoteAddr to get the end-user IP (I know of at least the X-Real-IP and X-Forwarded-For headers), I think that populating attributes from a request is an app-level concern rather than a library one.

**Comment by josharian** [comment]
OK. Although if IP address and user agent are important parts of the security story, I would make it easier to use them. Helpers for common setups (RemoteAddr, standard headers) will increase the odds that people actually do the integration.

**Comment by jeremy-stytch** [comment]
Yeah that's a great point, thanks for the feedback! We'll consider that more deeply when we start looking at better integrations with particular app frameworks or components.

Also, I just realized where I recognized your username from. Thanks for [impl](https://github.com/josharian/impl), I use it every day!

**Comment by josharian** [comment]
That's the first time someone has remembered me from impl. A pleasant surprise. :) I should really give it a few hours of attention. It's so easy to neglect open source projects.

**Pull request closed without merging**
