### PR TITLE
fix: missing Password field in UsersGetResponse

### PR DESCRIPTION
**Pull request by dechristopher**
This PR adds the missing `Password` field to the `UsersGetResponse` struct. The `User` struct has included the field since a60aae2b34dc6ac0d32973f6453b2315c74bf0c0. The `UsersGetResponse` was not changed to include it in the referenced commit.

### CODE REVIEW

**Comment by dechristopher** [comment]
Would love some eyes on this.

**Comment by dechristopher** [comment]
@danny-stytch @kaden-stytch  @nikhil-stytch @alex-stytch @grace-stytch

**Comment by dan-stytch** [comment]
Thanks @dechristopher for the PR and for the reminder! We'll work on getting this merged and getting a new version released

**Review by dan-stytch — APPROVED** [review]

**Comment by dan-stytch** [comment]
@dechristopher We've released [v6.5.1](https://github.com/stytchauth/stytch-go/releases/tag/v6.5.1) with your changes. Thanks again!

**Comment by dechristopher** [comment]
Many thanks!

**Pull request merged**
