### PR TITLE
Add Profile Picture and Locale to OAuth Provider

### PR DESCRIPTION
**Pull request by mia-stytch**

### CODE REVIEW

**Review by jeremy-stytch — APPROVED** [review]
Thanks! Update `APIVersion` in `stytch/config/config.go` before merging so you can match the version number on release. I think a minor version bump makes sense for support for a new API feature.

**Comment by josharian** [comment]
Thanks! Any change you want to tag the v5.4.2 release as well?

**Comment by cal-stytch** [comment]
@josharian just making sure everything is good on your end with the state of the library now

https://github.com/stytchauth/stytch-go/releases/tag/v5.4.2

**Comment by josharian** [comment]
Yep! I integrated the new version last night and got usable picture URLs out of it. Really appreciate the fast turnaround!

**Pull request merged**
